
name: "Baseline Compute"
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        default: 'factorial'
        type: choice
        options:
        - factorial
        - fibonacci
        - prime_count
      input_value:
        description: 'Input number'
        required: true
        default: '10'

jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Record start
        run: echo "START=$(date +%s%N)" >> $GITHUB_ENV
        
      - name: Baseline computation
        run: |
          operation="${{ github.event.inputs.operation || 'factorial' }}"
          input="${{ github.event.inputs.input_value || '10' }}"
          
          echo "🔄 Baseline: $operation($input)"
          
          case $operation in
            "factorial")
              result=1
              for i in $(seq 1 $input); do
                result=$((result * i))
              done
              ;;
            "fibonacci") 
              if [ $input -le 1 ]; then
                result=$input
              else
                a=0; b=1
                for i in $(seq 2 $input); do
                  temp=$((a + b)); a=$b; b=$temp
                done
                result=$b
              fi
              ;;
            "prime_count")
              result=0
              for n in $(seq 2 $input); do
                is_prime=1
                for i in $(seq 2 $((n/2))); do
                  if [ $((n % i)) -eq 0 ]; then is_prime=0; break; fi
                done
                if [ $is_prime -eq 1 ]; then result=$((result + 1)); fi
              done
              ;;
          esac
          
          echo "RESULT=$result" >> $GITHUB_ENV
          echo "✅ Baseline result: $result"
          
      - name: Record metrics
        run: |
          end=$(date +%s%N)
          duration=$(((end - START) / 1000000))
          echo "📊 BASELINE METRICS:"
          echo "Duration: ${duration}ms"
          echo "Result: $RESULT" 
          echo "Runner used: YES"
          echo "Compute cost: FULL"
